### ISSUE TITLE
RuntimeError GY-9960

### ISSUE THREAD

**Issue by dertobias** [adafruit/Adafruit_CircuitPython_APDS9960#44]
Hi all! 
i have this board:
https://www.berrybase.at/apds-9960-rgb-infrarot-gestensensor

but cant get it to work with my xiao nrf:

```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "adafruit_apds9960/apds9960.py", line 187, in __init__
RuntimeError: 
```
i2c address is the same as in library

thanks ahead

**Comment by dertobias** [comment]
commenting out line **186+187** 
seems to solve my problem.

```

 186       # if self._read8(_APDS9960_ID) != _DEVICE_ID:
 187       #     raise RuntimeError()

```

odd.
